server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://115.159.53.71:3306/blog
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
elasticsearch:
  host: 115.159.53.71
  port: 9200
  schemeName: http
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl